"""
git_manager.py - Version control operations for MCP server projects
"""

import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

import config_manager


def _run_git(
    cwd: str, *args: str, timeout: int = 30
) -> Dict[str, Any]:
    """Run a git command and return structured output."""
    try:
        proc = subprocess.run(
            ['git'] + list(args),
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return {
            "success": proc.returncode == 0,
            "stdout": proc.stdout.strip(),
            "stderr": proc.stderr.strip(),
            "returncode": proc.returncode,
        }
    except FileNotFoundError:
        return {"success": False, "stdout": "", "stderr": "git not found in PATH", "returncode": -1}
    except subprocess.TimeoutExpired:
        return {"success": False, "stdout": "", "stderr": "Command timed out", "returncode": -1}


def _get_server_path(server_name: str) -> str:
    """Get the working directory for a server."""
    try:
        config = config_manager.get_server_config(server_name)
        cwd = config.get("cwd", "")
        if cwd:
            return cwd
        # Try to infer from args
        args = config.get("args", [])
        for arg in args:
            p = Path(arg)
            if p.is_file():
                return str(p.parent)
            if p.is_dir():
                return str(p)
    except Exception:
        pass
    raise ValueError(f"Cannot determine project path for server '{server_name}'")


def init_repo(server_name: str) -> Dict[str, Any]:
    """Initialize a git repository for the server's project."""
    path = _get_server_path(server_name)
    result = _run_git(path, 'init')

    if result["success"]:
        # Create .gitignore if it doesn't exist
        gitignore = Path(path) / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(
                "# Auto-generated by universal-mcp-admin\n"
                "__pycache__/\n*.pyc\n*.pyo\n.env\n.venv/\nvenv/\n"
                "node_modules/\n.DS_Store\ntarget/\nbuild/\ndist/\n"
                "*.bak\n",
                encoding='utf-8'
            )
            _run_git(path, 'add', '.gitignore')

    return {
        "success": result["success"],
        "message": result["stdout"] or result["stderr"],
        "server_name": server_name,
        "path": path,
    }


def commit_changes(
    server_name: str,
    message: str,
    files: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Stage and commit changes."""
    path = _get_server_path(server_name)

    # Stage files
    if files:
        for f in files:
            _run_git(path, 'add', f)
    else:
        _run_git(path, 'add', '-A')

    # Commit
    result = _run_git(path, 'commit', '-m', message)

    if result["success"]:
        # Get commit hash
        hash_result = _run_git(path, 'rev-parse', '--short', 'HEAD')
        return {
            "success": True,
            "message": f"Committed: {message}",
            "commit_hash": hash_result.get("stdout", ""),
            "details": result["stdout"],
        }
    else:
        return {
            "success": False,
            "message": result["stderr"] or result["stdout"] or "Commit failed",
        }


def get_git_status(server_name: str) -> Dict[str, Any]:
    """Get git status for a server's project."""
    path = _get_server_path(server_name)

    # Check if it's a git repo
    check = _run_git(path, 'rev-parse', '--is-inside-work-tree')
    if not check["success"]:
        return {
            "success": False,
            "is_repo": False,
            "message": "Not a git repository",
            "path": path,
        }

    status = _run_git(path, 'status', '--porcelain')
    branch = _run_git(path, 'rev-parse', '--abbrev-ref', 'HEAD')

    files_changed: Dict[str, List[str]] = {
        "modified": [],
        "added": [],
        "deleted": [],
        "untracked": [],
    }
    for line in status.get("stdout", "").splitlines():
        if not line.strip():
            continue
        code = line[:2]
        fname = line[3:].strip()
        if 'M' in code:
            files_changed["modified"].append(fname)
        elif 'A' in code:
            files_changed["added"].append(fname)
        elif 'D' in code:
            files_changed["deleted"].append(fname)
        elif '?' in code:
            files_changed["untracked"].append(fname)

    return {
        "success": True,
        "is_repo": True,
        "branch": branch.get("stdout", "unknown"),
        "clean": not status.get("stdout", "").strip(),
        "files": files_changed,
        "path": path,
    }


def view_git_history(
    server_name: str, limit: int = 10
) -> Dict[str, Any]:
    """View recent commit history."""
    path = _get_server_path(server_name)
    result = _run_git(
        path, 'log', f'--max-count={limit}',
        '--format=%H|%h|%an|%ae|%s|%ci'
    )

    if not result["success"]:
        return {"success": False, "message": result["stderr"]}

    commits = []
    for line in result["stdout"].splitlines():
        parts = line.split('|', 5)
        if len(parts) >= 5:
            commits.append({
                "hash": parts[0],
                "short_hash": parts[1],
                "author": parts[2],
                "email": parts[3],
                "message": parts[4],
                "date": parts[5] if len(parts) > 5 else "",
            })

    return {
        "success": True,
        "commits": commits,
        "count": len(commits),
    }


def revert_commit(
    server_name: str, commit_hash: str
) -> Dict[str, Any]:
    """Revert a specific commit."""
    path = _get_server_path(server_name)
    result = _run_git(path, 'revert', '--no-edit', commit_hash)
    return {
        "success": result["success"],
        "message": result["stdout"] or result["stderr"],
    }


def create_branch(
    server_name: str, branch_name: str
) -> Dict[str, Any]:
    """Create and checkout a new branch."""
    path = _get_server_path(server_name)
    result = _run_git(path, 'checkout', '-b', branch_name)
    return {
        "success": result["success"],
        "message": result["stdout"] or result["stderr"],
        "branch": branch_name,
    }


def diff_changes(
    server_name: str, staged: bool = False
) -> Dict[str, Any]:
    """Show diff of current changes."""
    path = _get_server_path(server_name)
    args = ['diff']
    if staged:
        args.append('--staged')
    result = _run_git(path, *args)
    return {
        "success": result["success"],
        "diff": result["stdout"][:5000],  # Truncate large diffs
        "truncated": len(result["stdout"]) > 5000,
    }
